services:
  networthtracker:
    image: kpa90/networthtracker:latest
    container_name: networthtracker
    ports:
      - "8026:8000"
    volumes:
      - /opt/networthtracker/data:/app/data
    environment:
      DB_PATH: /app/data/networth.db
    restart: unless-stopped
